In [2]:
'''R2 score and accuracy are distinct metrics used for evaluating machine learning 
models, each suited to different types of problems:========>


R2 Score (Coefficient of Determination):-
Application: Primarily used in regression problems, where the goal is to predict a continuous numerical output.
Measures: The proportion of the variance in the dependent variable that can be explained by the independent variables in the regression 
model. It indicates how well the model fits the observed data.
Range: Typically ranges from 0 to 1, where 1 indicates a perfect fit (all variance explained), and 0 indicates no variance explained. 
A negative R2 score can occur if the model performs worse than a simple horizontal line at the mean of the dependent variable.


Accuracy Score:-
Application: Primarily used in classification problems, where the goal is to predict a categorical label or class.
Measures: The proportion of correctly classified instances out of the total number of instances. It directly indicates the correctness 
of the model's predictions.
Range: Ranges from 0 to 1, where 1 indicates perfect classification (all instances correctly classified), and 0 indicates no instances 
correctly classified.'''


from keras import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
a=sns.load_dataset("iris")
a

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder
la=LabelEncoder()
a["species"]=la.fit_transform(a["species"])

In [5]:
a

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [6]:
x=a.iloc[:,:-1]
y=a.iloc[:,-1]

In [7]:
# OneHotEncoding
from keras.utils import to_categorical
y=to_categorical(y,3)

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [9]:
model=Sequential()
model.add(Dense(9,input_dim=4,activation="relu"))
model.add(Dense(15,activation="relu"))
model.add(Dense(6,activation="relu"))
model.add(Dense(10,activation="relu"))
model.add(Dense(3,activation="relu"))

model.compile(Adam(learning_rate=0.01),loss = 'categorical_crossentropy')

d:\PYTHON_environment\ENV2\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 9)              │            45 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 15)             │           150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 6)              │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10)             │            70 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 3)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 394 (1.54 KB)

 Trainable params: 394 (1.54 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.fit(x_train,y_train,epochs=15,validation_split=0.2)

Epoch 1/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 3s 176ms/step - loss: nan - val_loss: nan
Epoch 2/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: nan - val_loss: nan
Epoch 3/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: nan - val_loss: nan
Epoch 4/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: nan - val_loss: nan
Epoch 5/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: nan - val_loss: nan
Epoch 6/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: nan - val_loss: nan
Epoch 7/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: nan - val_loss: nan
Epoch 8/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: nan - val_loss: nan
Epoch 9/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: nan - val_loss: nan
Epoch 10/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: nan - val_loss: nan
Epoch 11/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: nan - val_loss: nan
Epoch 12/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: nan - val_loss: nan
Epoch 13/15
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: nan - val_loss

In [12]:
pred=model.predict(x_test)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [13]:
p=np.argmax(pred,axis=1)
p

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [15]:
n=np.argmax(y_test,axis=1)
n

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [16]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score
accuracy_score(n,p)*100

33.33333333333333

In [17]:
recall_score(n,p,average='micro')

0.3333333333333333

In [18]:
precision_score(n,p,average='micro')

0.3333333333333333

In [19]:
f1_score(n,p,average='micro')

0.3333333333333333